// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCniCE38euxF5vm-y8omMC91O6eCX6qZH8',
    appId: '1:353322115976:web:b5190e980190aabff3503d',
    messagingSenderId: '353322115976',
    projectId: 'contacts-app-68ecd',
    authDomain: 'contacts-app-68ecd.firebaseapp.com',
    storageBucket: 'contacts-app-68ecd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmqCIOTSwBgq5hoi41FxpPPpzJ8U3VYYk',
    appId: '1:353322115976:android:9496f4e9c4c5c8d5f3503d',
    messagingSenderId: '353322115976',
    projectId: 'contacts-app-68ecd',
    storageBucket: 'contacts-app-68ecd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADx8z969d9GLx9Rq608-xPQtqC7yNrEn0',
    appId: '1:353322115976:ios:ad1e67d9b4e05c39f3503d',
    messagingSenderId: '353322115976',
    projectId: 'contacts-app-68ecd',
    storageBucket: 'contacts-app-68ecd.appspot.com',
    iosBundleId: 'com.example.myContactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADx8z969d9GLx9Rq608-xPQtqC7yNrEn0',
    appId: '1:353322115976:ios:2a9dfe88e10510ddf3503d',
    messagingSenderId: '353322115976',
    projectId: 'contacts-app-68ecd',
    storageBucket: 'contacts-app-68ecd.appspot.com',
    iosBundleId: 'com.example.myContactsApp.RunnerTests',
  );
}
